### ISSUE TITLE
Only working with Lua 5.3

### ISSUE THREAD

**Issue by Waces** [ers35/luastatic#21]
Both the most recent script from the git and the LuaRocks version work fine using 5.3 Lua, but always give an error when trying to use the other versions said to support (5.2, 5.1 and LuaJIT)

```
$ luastaic file.lua /usr/lib/libluajit-5.1.so /usr/bin/luajit-2.0.5
nm: /usr/lib/libluajit-5.1.so: no symbols
cc -Os file.lua.c  /usr/lib/libluajit-5.1.so -rdynamic -lm  -o input /usr/bin/luajit-2.0.5
/usr/bin/ld: /usr/bin/luajit-2.0.5: stderr: invalid version 2 (max 0)
/usr/bin/ld: /usr/bin/luajit-2.0.5: error adding symbols: bad value
collect2: error: ld returned 1 exit status
```
```
$ luastatic thing.lua /usr/lib/liblua5.2.so /usr/bin/lua5.2
nm: /usr/lib/liblua5.2.so: no symbols
cc -Os thing.lua.c  /usr/lib/liblua5.2.so -rdynamic -lm  -o thing /usr/bin/lua5.2
/usr/bin/ld: /tmp/ccq8PIjP.o: in function `msghandler':
thing.lua.c:(.text+0xe9): undefined reference to `lua_rotate'
/usr/bin/ld: thing.lua.c:(.text+0x111): undefined reference to `lua_rotate'
/usr/bin/ld: /tmp/ccq8PIjP.o: in function `main':
thing.lua.c:(.text.startup+0x105): undefined reference to `lua_rotate'
/usr/bin/ld: thing.lua.c:(.text.startup+0x151): undefined reference to `lua_rotate'
collect2: error: ld returned 1 exit status
```
_I may be just doing something wrong_

Tested on Manjaro(/Arch) x86_64

**Comment by ers35** [comment]
You shouldn't pass an executable file to luastatic.

Try these commands instead:
`luastatic file.lua -lluajit-5.1`
`luastatic thing.lua -llua5.2`

Passing -llua5.2 uses dynamic linking. Pass a .a file if you want to statically link Lua. See the [examples](https://github.com/ers35/luastatic#examples) in the readme.

**Comment by Waces** [comment]
Ah thanks :P 

I'm sorry, I'm not that used to linking to libs, the first try worked with 5.3 so I assumed it worked like that

I'm really sorry
